name: Validate Files

on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Print user
      run: echo "User is ${{ github.actor }}"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for unwanted files
      run: |
        base_sha=${{ github.event.pull_request.base.sha }}
        head_sha=${{ github.event.pull_request.head.sha }}
        changed_files=$(git diff --name-only $base_sha $head_sha)
        if echo "$changed_files" | grep -E '(^\.github/|^Dockerfile|^docker-compose.yml)'; then
          if [ "${{ github.actor }}" != "felipebs07" ]; then
            echo "Error: Committing files in .github/ or Docker-related files is not allowed unless you are felipebs."
            exit 1
          fi
        fi
